
import React, { useMemo } from 'react';
import { AiComparisonResult, ProposalTier, FullBoqItem } from '../../types';
import { formatCurrency, calculateSellPrice } from '../../lib/utils';

interface ClientMaterialSpecsProps {
    comparisonData: AiComparisonResult;
    tiers: { name: string, executionTotal: number, fullBoq?: FullBoqItem[] }[];
    isLevel2?: boolean;
}

// Helper to check room type for filtering
const WET_AREAS = ['Kitchen', 'Bath', 'Toilet', 'Wash', 'Utility', 'Dining'];
const checkRoom = (name: string | undefined, type: 'wet' | 'dry' | 'kitchen') => {
    if (!name) return false;
    const lower = name.toLowerCase();
    if (type === 'kitchen') return lower.includes('kitchen');
    if (type === 'wet') return WET_AREAS.some(w => lower.includes(w.toLowerCase()));
    if (type === 'dry') return !WET_AREAS.some(w => lower.includes(w.toLowerCase()));
    return false;
};

const ClientMaterialSpecs: React.FC<ClientMaterialSpecsProps> = ({ comparisonData, tiers, isLevel2 = false }) => {
    // If no data, return null to avoid empty section
    if (!tiers || tiers.length === 0) return null;

    // --- LOGIC FOR LEVEL 1 (COMPARISON) ---
    // Uses the generic matrix generated by `lib/comparison.ts`
    const l1OrderedKeys = [
        'Plywood (Kitchen & Bath)',
        'Plywood (Rest of House)',
        'Hardware System',
        'Laminate – Inner Finish',
        'Laminate – Outer Finish',
        'Wardrobe Drawers & Lofts',
        'Kitchen Shutters',
        'Paint Finish',
        'False Ceiling Material',
        'Electrical Fittings'
    ];

    const l1Rows = l1OrderedKeys.map(key => {
        const foundRow = (comparisonData.materialMatrix || []).find(r => r.feature === key);
        const rowObj: any = { category: key };
        tiers.forEach(t => {
            rowObj[t.name] = foundRow ? (foundRow[t.name] || '-') : '-';
        });
        return rowObj;
    });

    // --- LOGIC FOR LEVEL 2 (SPECIFIC - 3 Columns) ---
    // Generates [Category | Brand/Material | Notes/Rate]
    const l2Rows = useMemo(() => {
        if (!isLevel2 || !tiers[0]?.fullBoq) return [];
        
        const items = tiers[0].fullBoq;
        
        const specsConfig = [
            {
                category: 'Plywood (Kitchen & Bedrooms)',
                matcher: (i: FullBoqItem) => i.cat === 'Carpentry' || i.cat === 'Modular Kitchen',
                keywords: ['BWP', 'BWR', 'Marine', 'MR Grade', 'Commercial', '710', '303', 'Century', 'Greenply', 'Kitply'],
                defaultMat: 'Marine Grade & MR Grade'
            },
            {
                category: 'Laminate Finish',
                matcher: (i: FullBoqItem) => (i.specs || '').toLowerCase().includes('laminate') && !i.name.toLowerCase().includes('inner') && !i.specs.toLowerCase().includes('liner'),
                keywords: ['Merino', 'Greenlam', 'Royal Touche', 'Century', '1mm', '1.25mm', 'Acrylic', 'PU'],
                defaultMat: 'Merino/Century 600 Series'
            },
            {
                category: 'Kitchen Hardware',
                matcher: (i: FullBoqItem) => checkRoom(i.roomId, 'kitchen') && (i.cat === 'Hardware' || i.specs.toLowerCase().includes('hardware') || i.specs.toLowerCase().includes('channel') || i.cat === 'Modular Kitchen'),
                keywords: ['Hettich', 'Hafele', 'Blum', 'Tandem', 'Soft-close', 'Innotech'],
                defaultMat: 'Tandem Boxes (Hettich)'
            },
            {
                category: 'Wardrobe Hardware',
                matcher: (i: FullBoqItem) => !checkRoom(i.roomId, 'kitchen') && (i.cat === 'Hardware' || i.specs.toLowerCase().includes('hinge') || i.specs.toLowerCase().includes('channel') || i.name.toLowerCase().includes('drawer')),
                keywords: ['Soft-close', 'Hettich', 'Ebco', 'Godrej', 'Hinges', 'Channels'],
                defaultMat: 'Soft-close Hinges (Hettich/Ebco)'
            },
            {
                category: 'Wall Paint',
                matcher: (i: FullBoqItem) => i.cat === 'Painting' && !i.name.toLowerCase().includes('ceiling'),
                keywords: ['Royale', 'Apcolite', 'Asian Paints', 'Dulux', 'Velvet', 'Matt'],
                defaultMat: 'Asian Paints Royale'
            },
            {
                category: 'Ceiling Paint',
                matcher: (i: FullBoqItem) => i.cat === 'Painting' && i.name.toLowerCase().includes('ceiling'),
                keywords: ['Plastic', 'Emulsion', 'Tractor', 'Apcolite'],
                defaultMat: 'Plastic Emulsion'
            },
            {
                category: 'Electricals',
                matcher: (i: FullBoqItem) => i.cat === 'Electrical',
                keywords: ['Polycab', 'Finolex', 'Anchor', 'Legrand', 'GM', 'Schneider', 'Norisys', 'Havells'],
                defaultMat: 'Polycab Wires, Anchor Switches'
            },
            {
                category: 'False Ceiling',
                matcher: (i: FullBoqItem) => i.cat === 'Civil' && (i.name.toLowerCase().includes('ceiling') || i.name.toLowerCase().includes('pop')),
                keywords: ['Gypsum', 'Saint Gobain', 'POP', 'Grid'],
                defaultMat: 'Local A+ grade Gypsum'
            }
        ];

        return specsConfig.map(config => {
            const relevantItems = items.filter(i => config.matcher(i));
            
            // Extract Keywords
            const foundKeywords = new Set<string>();
            let minRate = Infinity;
            let maxRate = -Infinity;
            let unit = '';

            relevantItems.forEach(i => {
                const text = `${i.name} ${i.specs}`;
                config.keywords.forEach(k => {
                    if (text.toLowerCase().includes(k.toLowerCase())) foundKeywords.add(k);
                });
                
                const rate = calculateSellPrice(i.materials, i.labor, i.margin);
                if (rate > 0) {
                    if (rate < minRate) minRate = rate;
                    if (rate > maxRate) maxRate = rate;
                }
                if (i.unit && !unit) unit = i.unit;
            });

            const material = foundKeywords.size > 0 ? Array.from(foundKeywords).join(', ') : config.defaultMat;
            
            let notes = '';
            if (minRate !== Infinity && maxRate !== -Infinity) {
                if (['sq ft', 'rft'].includes(unit)) {
                    // Check for reasonable range to display
                    if (Math.abs(minRate - maxRate) < 5) {
                        notes = `${formatCurrency(minRate)}/${unit}`;
                    } else {
                        notes = `${formatCurrency(minRate)} - ${formatCurrency(maxRate)}/${unit}`;
                    }
                } else {
                    notes = 'As per selection';
                }
            } else {
                notes = 'As per design';
            }

            return {
                category: config.category,
                material: material,
                notes: notes
            };
        });

    }, [comparisonData, tiers, isLevel2]);


    const isSingleTier = tiers.length === 1;
    const sectionTitle = isLevel2 ? "Material Specifications" : "Detailed Specifications & Differences";
    const finalRows = isLevel2 ? l2Rows : l1Rows;

    return (
        <section id="material-specs" className="rounded-3xl border border-slate-200 bg-white shadow-sm p-6 md:p-8 scroll-mt-24">
            <div>
                <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    {isLevel2 ? 'Technical Specs' : (isSingleTier ? 'Specification Sheet' : 'Section 6')}
                </div>
                <h2 className="mt-2 text-2xl md:text-3xl font-extrabold tracking-tight text-slate-900">
                    {sectionTitle}
                </h2>
                {!isLevel2 && (
                    <p className="mt-2 text-slate-600 max-w-3xl">
                        {isSingleTier 
                            ? `Detailed material specifications for the ${tiers[0].name} package.`
                            : 'A detailed breakdown of the technical specifications and material grades proposed for each option.'
                        }
                    </p>
                )}
            </div>

            {/* DESKTOP VIEW: TABLE */}
            <div className="hidden md:block mt-6 border-2 border-slate-100 rounded-2xl overflow-hidden">
                <table className="w-full text-sm text-left border-collapse">
                    <thead>
                        <tr className="bg-slate-50 border-b border-slate-200">
                            {isLevel2 ? (
                                <>
                                    <th className="py-4 px-6 font-bold text-slate-800 w-1/4 border-r border-slate-200">Category</th>
                                    <th className="py-4 px-6 font-bold text-slate-800 w-1/2 border-r border-slate-200">Proposed Material/Brand</th>
                                    <th className="py-4 px-6 font-bold text-slate-800 w-1/4">Notes</th>
                                </>
                            ) : (
                                <>
                                    <th className={`py-4 px-6 font-bold text-slate-800 border-r border-slate-200 ${isSingleTier ? 'w-1/3' : 'w-1/4'}`}>Category</th>
                                    {tiers.map((tier, idx) => (
                                        <th key={tier.name} className={`py-4 px-6 font-bold text-slate-800 min-w-[200px] ${idx !== tiers.length - 1 ? 'border-r border-slate-200' : ''}`}>
                                            {!isSingleTier && (
                                                <span className="block text-[10px] font-normal text-slate-500 uppercase tracking-wide mb-1">Option {String.fromCharCode(65 + idx)}</span>
                                            )}
                                            {tier.name}
                                        </th>
                                    ))}
                                </>
                            )}
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                        {finalRows.map((row: any, idx) => (
                            <tr key={idx} className="group hover:bg-slate-50/50 transition-colors">
                                <td className="py-4 px-6 font-bold text-slate-900 border-r border-slate-100 bg-slate-50/30">
                                    {row.category}
                                </td>
                                {isLevel2 ? (
                                    <>
                                        <td className="py-4 px-6 text-slate-700 leading-relaxed align-top font-medium border-r border-slate-100">
                                            {row.material}
                                        </td>
                                        <td className="py-4 px-6 text-slate-500 leading-relaxed align-top text-xs">
                                            {row.notes}
                                        </td>
                                    </>
                                ) : (
                                    tiers.map((tier, tIdx) => (
                                        <td key={tier.name} className={`py-4 px-6 text-slate-700 leading-relaxed align-top ${tIdx !== tiers.length - 1 ? 'border-r border-slate-100' : ''}`}>
                                            <div className="whitespace-pre-line">{row[tier.name]}</div>
                                        </td>
                                    ))
                                )}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* MOBILE VIEW: STACKED CARDS */}
            <div className="md:hidden mt-6 space-y-4">
                {finalRows.map((row: any, idx) => (
                    <div key={idx} className="bg-slate-50 rounded-2xl p-5 border border-slate-200">
                        <h4 className="font-bold text-slate-900 text-sm mb-4 border-b border-slate-200 pb-2">{row.category}</h4>
                        <div className="space-y-4">
                            {isLevel2 ? (
                                <>
                                    <div>
                                        <p className="text-[10px] font-bold text-slate-400 uppercase">Material/Brand</p>
                                        <p className="text-sm font-bold text-slate-800">{row.material}</p>
                                    </div>
                                    <div>
                                        <p className="text-[10px] font-bold text-slate-400 uppercase">Notes</p>
                                        <p className="text-sm text-slate-600">{row.notes}</p>
                                    </div>
                                </>
                            ) : (
                                tiers.map((tier, tIdx) => (
                                    <div key={tier.name} className="flex flex-col gap-1">
                                        <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">{tier.name}</span>
                                        <span className="text-sm text-slate-800 font-medium bg-white p-2 rounded-lg border border-slate-100 shadow-sm">{row[tier.name]}</span>
                                    </div>
                                ))
                            )}
                        </div>
                    </div>
                ))}
            </div>
            
            <div className="mt-6 p-4 bg-slate-50 md:bg-white rounded-xl text-center md:border md:border-dashed md:border-slate-300">
                <p className="text-xs md:text-sm font-medium text-slate-500">
                    “Final brands, shades, and finishes will be selected based on sample approvals during project execution.”
                </p>
            </div>
        </section>
    );
};

export default ClientMaterialSpecs;
