import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ProjectContext } from '../types';
import Card from './shared/Card';
import { useOrg } from '../contexts/OrgContext';
import { usePaymentRequests } from '../hooks/usePaymentRequests';
import { WhatsAppReminderModal } from './WhatsAppReminderModal';
import { useStudioSettings } from '../hooks/useStudioSettings';
import { useEscalationProtocol } from '../hooks/useEscalationProtocol';
import { formatINR, timeAgo } from '../lib/utils';
import { buildWhatsAppURL, renderPaymentReminderMessage } from '../lib/whatsappUtils';
import { doc, updateDoc, setDoc, collection, onSnapshot } from 'firebase/firestore';
import { db } from '../services/firebaseClient';
import { 
  AlertTriangle, 
  CheckCircle2, 
  Clock, 
  IndianRupee, 
  ArrowRight, 
  ShieldAlert, 
  Hammer,
  Truck,
  Calendar,
  ChevronDown,
  ChevronUp,
  Activity,
  Zap,
  Unlock,
  Lock,
  PackageSearch,
  CheckSquare,
  FileText
} from 'lucide-react';

interface ExecutionWorkspaceProps {
  projectContext: ProjectContext;
  projectId: string;
  executionData?: any;
  onUpdateExecutionData?: (newData: any) => void;
  boq?: any[];
  onNavigateDrawings?: () => void;
}

// --- MOCK DATA: Simulating BOQ-Derived Intelligence ---
// In a real scenario, this is generated by scanning the BOQ categories.
const DERIVED_BUNDLES = [
  {
    id: 'b1',
    code: 'B-101',
    name: 'Civil & MEP Rough-in',
    trade: 'Civil',
    derivedFrom: ['Demolition', 'Masonry', 'Plumbing Rough-in', 'Electrical Conduiting'],
    status: 'completed' as any,
    isOverridden: false,
    gatekeepers: { sof: true, payment: true, site: true },
    actToday: '',
    breaksTomorrow: '',
    completionPercentage: 100,
    itemIds: [],
    totalValue: 0,
    gate: 'civil_start'
  },
  {
    id: 'b2',
    code: 'B-102',
    name: 'False Ceiling & Electrical',
    trade: 'Electrical',
    derivedFrom: ['Gypsum Ceiling', 'Grid Ceiling', 'Wiring & Switchboards'],
    status: 'active' as any,
    isOverridden: true,
    gatekeepers: { sof: false, payment: true, site: true },
    actToday: 'Force-started ceiling framing. MUST get AC duct routing approved today.',
    breaksTomorrow: 'If AC routing isn\'t approved, framing team sits idle tomorrow.',
    completionPercentage: 35,
    itemIds: [],
    totalValue: 0,
    gate: 'ceiling_start'
  },
  {
    id: 'b3',
    code: 'B-103',
    name: 'Carpentry & Carcass',
    trade: 'Carpentry',
    derivedFrom: ['Modular Kitchen', 'Wardrobes', 'Custom Paneling'],
    status: 'blocked' as any,
    isOverridden: false,
    gatekeepers: { sof: false, payment: false, site: false },
    actToday: 'Follow up on 50% advance payment for plywood procurement.',
    breaksTomorrow: 'Plywood vendor holding prices only until EOD.',
    completionPercentage: 0,
    itemIds: [],
    totalValue: 0,
    gate: 'carpentry_start'
  },
  {
    id: 'b4',
    code: 'B-104',
    name: 'Finishes & Handover',
    trade: 'Finishes',
    derivedFrom: ['Painting', 'Loose Furniture', 'Deep Cleaning'],
    status: 'pending' as any,
    isOverridden: false,
    gatekeepers: { sof: false, payment: false, site: false },
    actToday: 'Order custom sofa fabric immediately (4-week lead time).',
    breaksTomorrow: 'Sofa delivery will push past target handover date.',
    completionPercentage: 0,
    itemIds: [],
    totalValue: 0,
    gate: 'painting_start'
  }
];

const PROCUREMENT_RADAR = [
  { item: 'Plywood & Blockboard', bundle: 'Carpentry', leadTime: '3 days', status: 'critical', action: 'Release PO' },
  { item: 'Custom Sofa Fabric', bundle: 'Finishes', leadTime: '28 days', status: 'warning', action: 'Freeze SOF' },
  { item: 'Master Bed Veneer', bundle: 'Carpentry', leadTime: '14 days', status: 'pending', action: 'Client Approval' },
];

function EscalationBanner({ projectContext, projectId }: { projectContext: ProjectContext, projectId: string }) {
    const { orgData } = useOrg();
    const studioId = orgData?.tenantId || 'demo-tenant-01';
    useEscalationProtocol(projectId, studioId, projectContext); // Trigger escalation check
    
    const { paymentRequests } = usePaymentRequests(projectId, studioId);
    const { settings } = useStudioSettings(studioId);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [modalData, setModalData] = useState<{message: string, phone: string, item: any} | null>(null);

    const checkStatus = paymentRequests.filter(r => (r.status === 'pending' || r.status === 'overdue') && (r.escalationLevel && r.escalationLevel > 0));
    const highestEscalation = checkStatus.sort((a, b) => (b.escalationLevel || 0) - (a.escalationLevel || 0))[0];

    if (!highestEscalation) return null;

    const level = highestEscalation.escalationLevel || 0;
    const triggeredDate = highestEscalation.triggeredAt?.toDate ? highestEscalation.triggeredAt.toDate() : new Date(highestEscalation.triggeredAt);
    const daysPending = Math.floor((Date.now() - triggeredDate.getTime()) / (1000 * 60 * 60 * 24));

    const handlePrepareReminder = () => {
         const template = settings?.emailTemplates?.paymentRequest || '';
         const defaultTemplate = "Hi {clientName}, this is a gentle reminder that payment for {milestone} (₹{amount}) is due for your {projectName} project. Please let us know once processed. Thank you! — {studioName}";
         const variables = {
             clientName: projectContext?.clientName || 'Client',
             projectName: projectContext?.name || 'Project',
             studioName: settings?.companyName || 'Our Studio',
             amount: highestEscalation.amount ? highestEscalation.amount.toLocaleString('en-IN') : '0',
             milestone: highestEscalation.milestoneLabel,
             daysPending,
             supportContact: settings?.clientPortalConfig?.supportContact || ''
         };
         const message = renderPaymentReminderMessage(template || defaultTemplate, variables);
         const phone = projectContext?.clientPhone || '';
         setModalData({ message, phone, item: highestEscalation });
         setIsModalOpen(true);
    };

    const confirmSendReminder = (msg: string, ph: string) => {
         const url = buildWhatsAppURL(ph, msg);
         window.open(url, '_blank');
         setIsModalOpen(false);
    };

    const handleToggleWorkPaused = async () => {
         try {
             // We update the DB directly so it flows down everywhere!
             const newStatus = projectContext.status === 'work_paused' ? 'execution' : 'work_paused';
             const ref = doc(db, `studios/${studioId}/projects`, projectId);
             await setDoc(ref, { "context.status": newStatus }, { merge: true });
             // Attempt standard project collection if that is where it's stored instead:
             const ref2 = doc(db, `projects`, projectId);
             await setDoc(ref2, { status: newStatus }, { merge: true });
         } catch(e) { console.error("Error setting work_paused", e); }
    };
    
    let BannerDetails = { bg: '', border: '', text: '', icon: AlertTriangle, title: '', cta: 'Send Reminder', showPause: false };
    
    if (level === 1) {
       BannerDetails = { bg: 'bg-amber-100', border: 'border-amber-200', text: 'text-amber-800', icon: Clock, title: `⏳ Payment reminder due for ${highestEscalation.milestoneLabel} · ${daysPending} days since raised`, cta: 'Send WhatsApp Reminder', showPause: false };
    } else if (level === 2) {
       BannerDetails = { bg: 'bg-orange-100', border: 'border-orange-200', text: 'text-orange-900', icon: AlertTriangle, title: `⚠️ Payment overdue — ${highestEscalation.milestoneLabel} · ${daysPending} days · ₹${highestEscalation.amount} outstanding`, cta: 'Send Reminder', showPause: false };
    } else if (level === 3) {
       BannerDetails = { bg: 'bg-rose-100', border: 'border-rose-300', text: 'text-rose-900', icon: ShieldAlert, title: `🔴 Work Pause Advisory — Payment of ₹${highestEscalation.amount} for ${highestEscalation.milestoneLabel} is ${daysPending} days overdue.`, cta: 'Send Final Reminder', showPause: true };
    }

    const { icon: Icon } = BannerDetails;

    return (
        <div className={`mb-6 p-4 rounded-xl border ${BannerDetails.bg} ${BannerDetails.border} shadow-sm w-full font-sans`}>
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="flex items-start gap-3">
                    <div className={`p-2 rounded-full bg-white/50 border border-white/50 ${BannerDetails.text}`}>
                        <Icon className="w-5 h-5" />
                    </div>
                    <div>
                        <h4 className={`text-sm tracking-tight font-bold ${BannerDetails.text}`}>{BannerDetails.title}</h4>
                        {level === 3 && (
                            <p className={`text-xs mt-1 ${BannerDetails.text} opacity-90`}>
                                Consider pausing work on this project until payment is received. This protects your studio.
                            </p>
                        )}
                    </div>
                </div>
                <div className="flex flex-wrap items-center gap-2 shrink-0">
                    <button 
                        onClick={handlePrepareReminder}
                        className={`text-xs font-bold px-3 py-1.5 rounded-lg border bg-white shadow-sm hover:bg-slate-50 transition-colors ${BannerDetails.text}`}
                    >
                        {BannerDetails.cta}
                    </button>
                    {level >= 2 && (
                        <button className="text-[11px] font-bold px-3 py-1.5 rounded-lg bg-transparent text-slate-700 hover:bg-black/5 transition-colors">
                            Log a note
                        </button>
                    )}
                    {level === 3 && (
                        <button 
                            onClick={handleToggleWorkPaused}
                            className="text-[11px] font-bold px-3 py-1.5 rounded-lg bg-rose-600 text-white hover:bg-rose-700 shadow-sm transition-colors"
                        >
                            {projectContext.status === 'work_paused' ? 'Resume Project' : 'Mark as Work Paused'}
                        </button>
                    )}
                </div>
            </div>
            
            {isModalOpen && modalData && (
                <WhatsAppReminderModal 
                   isOpen={isModalOpen}
                   onClose={() => setIsModalOpen(false)}
                   onSend={confirmSendReminder}
                   template={settings?.emailTemplates?.paymentRequest || ''}
                   variables={{
                       clientName: projectContext?.clientName || 'Client',
                       projectName: projectContext?.name || 'Project',
                       studioName: settings?.companyName || 'Our Studio',
                       amount: modalData.item.amount ? modalData.item.amount.toLocaleString('en-IN') : '0',
                       milestone: modalData.item.milestoneLabel,
                       daysPending,
                       supportContact: settings?.clientPortalConfig?.supportContact || ''
                   }}
                   clientPhone={modalData.phone}
                />
            )}
        </div>
    );
}

function PaymentStatusWidget({ projectContext, projectId }: { projectContext: ProjectContext, projectId: string }) {
  const { orgData, currentUserAuth } = useOrg();
  const { settings } = useStudioSettings(orgData?.tenantId || 'demo-tenant-01');
  const { activeRequest, paymentRequests, markAsReceived, markReminderSent } = usePaymentRequests(projectId, orgData?.tenantId || 'demo-tenant-01');
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [showHistory, setShowHistory] = useState(false);

  if (activeRequest) {
    const isOverdue = activeRequest.status === 'overdue';
    const triggeredDate = activeRequest.triggeredAt.toDate ? activeRequest.triggeredAt.toDate() : new Date(activeRequest.triggeredAt);
    const daysSince = Math.ceil((Date.now() - triggeredDate.getTime()) / (1000 * 60 * 60 * 24));
    
    // Check if reminder is in cooldown
    const lastReminderTime = activeRequest.lastReminderAt?.toDate ? activeRequest.lastReminderAt.toDate().getTime() : (activeRequest.lastReminderAt ? new Date(activeRequest.lastReminderAt).getTime() : 0);
    const hoursSinceLastReminder = (Date.now() - lastReminderTime) / (1000 * 60 * 60);
    const isCooldown = hoursSinceLastReminder < 24 && lastReminderTime > 0;
    
    const handleSendReminder = (message: string, phone: string) => {
        const url = buildWhatsAppURL(phone, message);
        window.open(url, '_blank');
        markReminderSent(activeRequest.id, currentUserAuth?.uid || 'Unknown', message.substring(0, 100));
        setIsModalOpen(false);
    };

    const template = settings?.emailTemplates?.paymentRequest || '';
    const variables = {
        clientName: projectContext.clientName || 'Client',
        projectName: projectContext.name,
        studioName: settings?.companyName || 'Our Studio',
        amount: formatINR(activeRequest.amount || 0),
        milestone: activeRequest.milestoneLabel,
        daysPending: daysSince,
        supportContact: settings?.clientPortalConfig?.supportContact || ''
    };

    return (
      <>
        <div className={`p-5 flex flex-col justify-center rounded-2xl border shadow-sm ${
          isOverdue ? 'bg-red-50 border-red-200' : 'bg-amber-50 border-amber-200'
        }`}>
          <div className="flex items-center gap-4 mb-3">
              <div className={`p-3 rounded-xl ${
                isOverdue ? 'bg-red-100 text-red-600' : 'bg-amber-100 text-amber-600'
              }`}>
                <IndianRupee className="w-6 h-6" />
              </div>
              <div>
                <p className={`text-[10px] font-bold uppercase tracking-widest mb-1 ${isOverdue ? 'text-red-700' : 'text-amber-700'}`}>
                  {isOverdue ? `Overdue (${daysSince} Days)` : `Pending Payment`}
                </p>
                <h3 className="text-base font-bold text-slate-800 leading-none">
                  {activeRequest.milestoneLabel} · {activeRequest.amount ? `₹${activeRequest.amount.toLocaleString('en-IN')}` : '₹ TBC'}
                </h3>
              </div>
          </div>
          
          <div className="flex flex-col gap-3">
              <div className="flex gap-2">
                  <button 
                     onClick={() => {
                       const amountStr = window.prompt("Confirm amount received:", activeRequest.amount ? activeRequest.amount.toString() : '');
                       if (amountStr !== null) {
                         markAsReceived(activeRequest.id, Number(amountStr), new Date().toISOString());
                       }
                     }}
                     className="text-[10px] font-bold bg-emerald-100 hover:bg-emerald-200 text-emerald-800 px-3 py-1.5 rounded-md transition-colors"
                  >
                    Mark Received
                  </button>
                  <div className="relative group">
                      <button 
                         onClick={() => setIsModalOpen(true)}
                         disabled={isCooldown}
                         className="text-[10px] font-bold bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 px-3 py-1.5 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                         Send Reminder
                      </button>
                      {isCooldown && (
                          <div className="absolute top-full left-0 mt-1 opacity-0 group-hover:opacity-100 bg-slate-800 text-white text-[10px] rounded px-2 py-1 pointer-events-none transition-opacity font-medium z-10 w-48 shadow-lg">
                             Last reminder sent {Math.floor(hoursSinceLastReminder)}h ago. Wait 24h before sending again.
                          </div>
                      )}
                  </div>
                  {isCooldown && (
                      <button 
                        onClick={() => setIsModalOpen(true)}
                        className="text-[10px] font-bold text-slate-500 hover:text-slate-700 underline px-1 py-1.5"
                      >
                        Send anyway
                      </button>
                  )}
              </div>
              
              {activeRequest.reminderCount ? (
                  <div className="mt-1 pt-3 border-t border-slate-200/50">
                      <button 
                          onClick={() => setShowHistory(!showHistory)}
                          className="flex items-center gap-1 text-[10px] font-bold text-slate-500 hover:text-slate-700 uppercase tracking-widest"
                      >
                          {activeRequest.reminderCount} reminder{activeRequest.reminderCount !== 1 ? 's' : ''} sent
                          {showHistory ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                      </button>
                      {showHistory && activeRequest.reminderLog && (
                          <div className="mt-2 space-y-2">
                              {activeRequest.reminderLog.map((log, idx) => (
                                  <div key={idx} className="bg-white/50 rounded-lg p-2 text-xs text-slate-600 border border-slate-100">
                                      <div className="flex justify-between items-center mb-1">
                                          <span className="font-semibold text-slate-700">{timeAgo(new Date(log.sentAt).getTime())}</span>
                                      </div>
                                      <p className="opacity-80 truncate" title={log.messagePreview}>{log.messagePreview}...</p>
                                  </div>
                              ))}
                          </div>
                      )}
                      
                      {/* Escalation Timeline */}
                      {showHistory && settings?.paymentMilestones?.escalation && (
                          <div className="mt-4 pt-4 border-t border-slate-200/50">
                              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-3">Escalation Ladder</p>
                              <div className="space-y-4 pl-2 border-l-2 border-slate-200 relative">
                                  {[
                                      { label: "Payment Raised", day: 0, reached: true },
                                      { label: "First Reminder", day: settings.paymentMilestones.escalation.reminderDays, reached: daysSince >= settings.paymentMilestones.escalation.reminderDays },
                                      { label: "At Risk Flag", day: settings.paymentMilestones.escalation.warnDays, reached: daysSince >= settings.paymentMilestones.escalation.warnDays },
                                      { label: "Work Pause Advisory", day: settings.paymentMilestones.escalation.pauseDays, reached: daysSince >= settings.paymentMilestones.escalation.pauseDays }
                                  ].map((step, i) => (
                                      <div key={i} className="relative flex items-center">
                                          <div className={`absolute -left-[13px] w-5 h-5 rounded-full flex items-center justify-center border-2 bg-white ${step.reached ? 'border-emerald-500 text-emerald-500' : 'border-slate-300 text-slate-300'}`}>
                                              {step.reached ? <CheckCircle2 className="w-3 h-3" /> : <div className="w-1.5 h-1.5 bg-slate-200 rounded-full" />}
                                          </div>
                                          <div className="ml-6 flex w-full justify-between items-center">
                                              <span className={`text-[11px] font-bold ${step.reached ? 'text-slate-800' : 'text-slate-400'}`}>{step.label}</span>
                                              <span className="text-[10px] font-medium text-slate-400">Day {step.day}</span>
                                          </div>
                                      </div>
                                  ))}
                              </div>
                          </div>
                      )}
                  </div>
              ) : null}
          </div>
        </div>
        
        <WhatsAppReminderModal 
            isOpen={isModalOpen}
            onClose={() => setIsModalOpen(false)}
            onSend={handleSendReminder}
            template={template}
            variables={variables}
            clientPhone={projectContext.clientPhone || ''}
        />
      </>
    );
  }

  const lastReceived = paymentRequests.find(r => r.status === 'received');
  
  return (
      <div className="p-5 rounded-2xl border border-slate-200 bg-white flex items-center gap-4 shadow-sm flex-1">
        <div className="p-3 rounded-xl bg-slate-100 text-slate-400">
          <CheckCircle2 className="w-6 h-6" />
        </div>
        <div>
          <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Financial Health</p>
          <h3 className="text-base font-bold text-slate-800 leading-none">
            {lastReceived 
              ? `Last: ${lastReceived.milestoneLabel}`
              : 'No payments raised yet'}
          </h3>
          {lastReceived && (
              <p className="text-xs font-mono font-medium text-emerald-600 mt-1">₹{(lastReceived.receivedAmount || lastReceived.amount || 0).toLocaleString('en-IN')} Received</p>
          )}
        </div>
      </div>
  );
}

const BUNDLE_DRAWING_INDEX: Record<string, string[]> = {
  woodwork: ['elevation_room', 'carpentry_detail_room'],
  ceiling: ['ceiling_layout', 'electrical_looping_layout'],
  plumbing: ['sanitary_layout', 'waterproofing_layout'],
  modular_kitchen: ['kitchen_elevation', 'kitchen_detail_drawing'],
  flooring: ['floor_layout'],
  civil: ['demolition_layout'],
  hvac: ['hvac_layout'],
  electrical: ['electrical_looping_layout']
};

const BUNDLE_CATEGORY_MAP: Record<string, string> = {
  'EB-02': 'civil',
  'EB-03': 'electrical',
  'EB-04': 'plumbing',
  'EB-05': 'ceiling',
  'EB-06': 'flooring',
  'EB-07': 'woodwork',
  'EB-08': 'ceiling',
  'EB-10': 'woodwork',
  'EB-11': 'electrical'
};

export const computeBundlesWithGates = (bundles: any[], allDrawings: any[], boq: any[]): any[] => {
  return bundles.map(b => {
    const mappedCat = BUNDLE_CATEGORY_MAP[b.code];
    if (!mappedCat) return b;

    const config = BUNDLE_DRAWING_INDEX[mappedCat];
    if (!config) return b;

    const matched = allDrawings.filter(d => {
      if (mappedCat === 'woodwork') {
        return d.id.startsWith('elevation_room_') || d.id.startsWith('carpentry_detail_room_') || d.id.includes('elevation') || d.id.includes('carpentry');
      }
      return config.some(pattern => d.id === pattern || d.id.startsWith(pattern) || d.id.includes(pattern));
    });

    const missingDrawings = matched.filter(d => !d.gfc || d.gfc.status !== 'issued');
    const isGfcComplete = matched.length > 0 && missingDrawings.length === 0;

    const blockedReason = !isGfcComplete && matched.length > 0
      ? `${missingDrawings.length} drawing(s) not GFC: ${missingDrawings.map(d => d.name).join(', ')}`
      : (!isGfcComplete ? "Matching GFC drawings are missing or pending issuance" : "");

    const unblocksValue = b.totalValue || 0;

    // Detect if already overridden in current data
    const existingGate = typeof b.gate === 'object' ? b.gate : null;
    const wasOverridden = b.isOverridden || (existingGate && existingGate.status === 'in_progress');

    let gateStatus: 'blocked' | 'ready' | 'in_progress' = isGfcComplete 
      ? 'ready' 
      : (wasOverridden ? 'in_progress' : 'blocked');

    const newGate = {
      requiresGfc: true,
      status: gateStatus,
      blockedReason,
      unblocksValue,
      overrideAudit: existingGate?.overrideAudit || b.overrideAudit || null
    };

    const gates = b.gatekeepers || { sof: false, payment: false, site: false };
    const allGatesCleared = gates.sof && gates.payment && gates.site;

    let finalStatus = b.status;
    if (b.status !== 'completed') {
      if (gateStatus === 'blocked') {
        finalStatus = 'blocked';
      } else if (gateStatus === 'in_progress') {
        finalStatus = 'active';
      } else if (isGfcComplete) {
        finalStatus = allGatesCleared ? 'active' : 'blocked';
        if (b.status === 'blocked' && allGatesCleared) {
          finalStatus = 'active';
        }
      }
    }

    return {
      ...b,
      gate: newGate,
      status: finalStatus,
      isOverridden: wasOverridden
    };
  });
};

const ExecutionWorkspace: React.FC<ExecutionWorkspaceProps> = ({ 
  projectContext, 
  projectId, 
  executionData, 
  onUpdateExecutionData,
  boq = [],
  onNavigateDrawings
}) => {
  const bundles = executionData?.bundles && executionData.bundles.length > 0 ? executionData.bundles : DERIVED_BUNDLES;
  
  const { orgData, currentRole, currentUserAuth } = useOrg();
  const orgId = orgData?.tenantId || 'demo-tenant-01';
  const isOwner = ['Super Admin', 'Admin', 'Ops Director', 'Owner'].includes(currentRole || '');

  const [allDrawings, setAllDrawings] = useState<any[]>([]);
  const [overrideBundleId, setOverrideBundleId] = useState<string | null>(null);
  const [overrideReason, setOverrideReason] = useState('');

  // 1. Listen to global or nested drawingTracker collection
  useEffect(() => {
    if (!projectId || !orgId) return;
    const unsub = onSnapshot(collection(db, `organizations/${orgId}/projects/${projectId}/drawingTracker`), (snap) => {
      const list = snap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setAllDrawings(list);
    }, (err) => {
      console.error("Failed to fetch drawing tracker for workspace", err);
    });
    return () => unsub();
  }, [projectId, orgId]);

  // 2. Automatically sync recalculated bundle state back to Firestore if difference detected
  useEffect(() => {
    if (allDrawings.length === 0 || !onUpdateExecutionData || !executionData?.bundles) return;
    const currentBundles = executionData.bundles;
    const computed = computeBundlesWithGates(currentBundles, allDrawings, boq);

    // Evaluate difference without causing render loop
    let hasDiff = false;
    for (let i = 0; i < computed.length; i++) {
      const bA = computed[i];
      const bB = currentBundles[i];
      if (!bB) { hasDiff = true; break; }
      if (bA.status !== bB.status) { hasDiff = true; break; }
      if (bA.isOverridden !== bB.isOverridden) { hasDiff = true; break; }
      
      const gateA = bA.gate;
      const gateB = bB.gate;
      if (typeof gateA === 'object' && typeof gateB === 'object') {
        if (gateA.status !== gateB.status || 
            gateA.blockedReason !== gateB.blockedReason || 
            gateA.unblocksValue !== gateB.unblocksValue) {
          hasDiff = true;
          break;
        }
      } else if (typeof gateA !== typeof gateB) {
        hasDiff = true;
        break;
      }
    }

    if (hasDiff) {
      console.log("Recalculated companion and GFC blockages, syncing changes to DB...");
      onUpdateExecutionData({
        ...executionData,
        bundles: computed
      });
    }
  }, [allDrawings, executionData?.bundles, boq, onUpdateExecutionData]);

  const [expandedBundle, setExpandedBundle] = useState<string | null>('b2');
  const [activeTab, setActiveTab] = useState<'frontline' | 'radar' | 'logs'>('frontline');

  const activeBundle = bundles.find(b => b.status === 'active');
  const blockedCount = (bundles || []).filter(b => b.status === 'blocked').length;
  const threatLevel = blockedCount > 0 ? 'critical' : activeBundle?.isOverridden ? 'warning' : 'stable';

  const updateBundles = (newBundles: any[]) => {
      if (onUpdateExecutionData) {
          onUpdateExecutionData({ ...executionData, bundles: newBundles });
      }
  };

  const handleProceedAtRisk = (bundleId: string, reason: string) => {
    if (!isOwner) {
      alert("Permission denied: \"Proceed at risk\" override is Owner-only.");
      return;
    }
    if (!reason.trim()) {
      alert("Please provide an override justification reason.");
      return;
    }

    const nextBundles = bundles.map(b => {
      if (b.id === bundleId) {
        const existingGate = typeof b.gate === 'object' ? b.gate : {};
        const updatedGate = {
          ...existingGate,
          status: 'in_progress' as const,
          overrideAudit: {
            by: currentUserAuth?.email || 'Owner Account',
            at: Date.now(),
            reason: reason.trim()
          }
        };
        return {
          ...b,
          isOverridden: true,
          status: 'active' as const,
          gate: updatedGate
        };
      }
      return b;
    });

    updateBundles(nextBundles);
    setOverrideBundleId(null);
    setOverrideReason('');
  };

  const toggleOverride = (bundleId: string) => {
    updateBundles(bundles.map(b => {
      if (b.id === bundleId) {
        const newOverride = !b.isOverridden;
        const gates = b.gatekeepers || { sof: false, payment: false, site: false };
        const allGatesCleared = gates.sof && gates.payment && gates.site;
        const newStatus = newOverride ? 'active' : (allGatesCleared ? 'pending' : 'blocked');
        return { ...b, isOverridden: newOverride, status: newStatus };
      }
      return b;
    }));
  };

  const toggleGatekeeper = (bundleId: string, gate: 'sof' | 'payment' | 'site') => {
    updateBundles(bundles.map(b => {
      if (b.id === bundleId) {
        const gates = b.gatekeepers || { sof: false, payment: false, site: false };
        const newGates = { ...gates, [gate]: !gates[gate] };
        const allGatesCleared = newGates.sof && newGates.payment && newGates.site;
        let newStatus = b.status;
        if (!b.isOverridden && b.status !== 'completed') {
            newStatus = allGatesCleared ? 'pending' : 'blocked';
        }
        return { ...b, gatekeepers: newGates, status: newStatus };
      }
      return b;
    }));
  };

  return (
    <div className="space-y-6 font-sans max-w-6xl mx-auto">
      
      <EscalationBanner projectContext={projectContext} projectId={projectId} />

      {/* LAYER 1: The Command Center (Insights) */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Threat Matrix */}
        <div className={`p-5 rounded-2xl border flex items-center gap-4 ${
          threatLevel === 'critical' ? 'bg-rose-50 border-rose-200' : 
          threatLevel === 'warning' ? 'bg-amber-50 border-amber-200' : 
          'bg-emerald-50 border-emerald-200'
        }`}>
          <div className={`p-3 rounded-xl ${
            threatLevel === 'critical' ? 'bg-rose-100 text-rose-600' : 
            threatLevel === 'warning' ? 'bg-amber-100 text-amber-600' : 
            'bg-emerald-100 text-emerald-600'
          }`}>
            {threatLevel === 'critical' ? <ShieldAlert className="w-6 h-6" /> : 
             threatLevel === 'warning' ? <AlertTriangle className="w-6 h-6" /> : 
             <Activity className="w-6 h-6" />}
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Site Health</p>
            <h3 className={`text-base font-bold leading-none ${
              threatLevel === 'critical' ? 'text-rose-700' : 
              threatLevel === 'warning' ? 'text-amber-700' : 
              'text-emerald-700'
            }`}>
              {threatLevel === 'critical' ? `${blockedCount} Blocked Bundles` : 
               threatLevel === 'warning' ? 'Active via Override' : 
               'Execution on Track'}
            </h3>
          </div>
        </div>

        {/* Timeline Insight */}
        <div className="p-5 rounded-2xl border border-slate-200 bg-white flex items-center gap-4 shadow-sm">
          <div className="p-3 rounded-xl bg-slate-100 text-slate-600">
            <Calendar className="w-6 h-6" />
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Target Handover</p>
            <div className="flex items-baseline gap-2">
                <h3 className="text-base font-bold text-slate-800 leading-none">
                {projectContext?.targetHandoverDate ? new Date(projectContext.targetHandoverDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' }) : '10 May'}
                </h3>
                <span className="text-xs font-mono font-medium text-slate-400">47 Days Left</span>
            </div>
          </div>
        </div>

        {/* Payment Pending Widget (Financial Insight) bg-white or warning state */}
        <PaymentStatusWidget projectContext={projectContext} projectId={projectId} />
      </div>

      {/* Latest Site Updates Ticker */}
      {executionData?.updates && executionData.updates.length > 0 && (
          <div className="p-4 rounded-xl border border-indigo-100 bg-indigo-50/50 flex flex-col md:flex-row gap-4">
              <div className="flex items-center gap-2 shrink-0">
                  <div className="relative flex h-3 w-3">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-3 w-3 bg-indigo-500"></span>
                  </div>
                  <span className="text-[10px] font-bold uppercase tracking-widest text-indigo-800">Latest from Site</span>
              </div>
              <div className="flex-1 text-sm font-medium text-slate-800 border-l border-indigo-200 pl-4 space-y-1">
                  <p>{executionData.updates[0].text}</p>
                  <p className="text-xs text-slate-500">
                      — {executionData.updates[0].author} · {timeAgo(executionData.updates[0].timestamp)}
                  </p>
              </div>
          </div>
      )}

      {/* Workspace Navigation */}
      <div className="flex gap-2 border-b border-slate-200 pb-px">
        <button 
            onClick={() => setActiveTab('frontline')}
            className={`px-6 py-3 text-sm font-bold uppercase tracking-wider transition-colors border-b-2 ${activeTab === 'frontline' ? 'border-slate-900 text-slate-900' : 'border-transparent text-slate-400 hover:text-slate-600'}`}
        >
            Execution Frontline
        </button>
        <button 
            onClick={() => setActiveTab('radar')}
            className={`px-6 py-3 text-sm font-bold uppercase tracking-wider transition-colors border-b-2 flex items-center gap-2 ${activeTab === 'radar' ? 'border-slate-900 text-slate-900' : 'border-transparent text-slate-400 hover:text-slate-600'}`}
        >
            Procurement Radar
            <span className="bg-rose-100 text-rose-600 px-1.5 py-0.5 rounded text-[10px]">2</span>
        </button>
      </div>

      {/* Tab Content */}
      <AnimatePresence mode="wait">
        {activeTab === 'frontline' ? (
          <motion.div 
            key="frontline"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="space-y-4"
          >
            {bundles.map((bundle) => {
              const isExpanded = expandedBundle === bundle.id;
              const isOverridden = bundle.isOverridden;
              
              return (
                <div 
                    key={bundle.id} 
                    className={`bg-white rounded-2xl border overflow-hidden transition-all duration-300 ${
                        bundle.status === 'active' ? 'shadow-md border-slate-300' : 'shadow-sm border-slate-200'
                    } ${isOverridden ? 'ring-2 ring-amber-400/50' : ''}`}
                >
                  {/* Warning Tape for Overrides */}
                  {isOverridden && (
                      <div className="h-1.5 w-full" style={{ backgroundImage: 'repeating-linear-gradient(45deg, #fbbf24, #fbbf24 10px, #f59e0b 10px, #f59e0b 20px)' }}></div>
                  )}

                  {/* Bundle Header (Clickable) */}
                  <div 
                    className={`p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 cursor-pointer hover:bg-slate-50 transition-colors ${bundle.status === 'completed' ? 'opacity-60 grayscale' : ''}`}
                    onClick={() => setExpandedBundle(isExpanded ? null : bundle.id)}
                  >
                    <div className="flex items-center gap-4">
                        <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${
                            bundle.status === 'completed' ? 'bg-slate-100 text-slate-400' :
                            bundle.status === 'active' ? 'bg-emerald-100 text-emerald-600' :
                            bundle.status === 'blocked' ? 'bg-rose-100 text-rose-600' :
                            'bg-slate-100 text-slate-500'
                        }`}>
                            {bundle.status === 'completed' ? <CheckCircle2 className="w-5 h-5" /> :
                             bundle.status === 'active' ? <Hammer className="w-5 h-5" /> :
                             bundle.status === 'blocked' ? <ShieldAlert className="w-5 h-5" /> :
                             <Clock className="w-5 h-5" />}
                        </div>
                        <div>
                            <div className="flex items-center gap-2">
                                <h3 className="text-lg font-bold text-slate-800">{bundle.name}</h3>
                                {isOverridden && <span className="px-2 py-0.5 bg-amber-100 text-amber-700 text-[9px] font-bold uppercase tracking-widest rounded border border-amber-200">Ops Override</span>}
                            </div>
                            <p className="text-[10px] font-mono text-slate-400 uppercase tracking-wider mt-1">
                                Derived from: {bundle.derivedFrom.length} BOQ Items
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-6">
                        {/* Mini Gatekeeper Status */}
                        {bundle.status !== 'completed' && (
                            <div className="hidden md:flex gap-1">
                                <div className={`w-2 h-2 rounded-full ${bundle.gatekeepers.sof ? 'bg-emerald-400' : 'bg-slate-200'}`} title="SOF"></div>
                                <div className={`w-2 h-2 rounded-full ${bundle.gatekeepers.payment ? 'bg-emerald-400' : 'bg-slate-200'}`} title="Payment"></div>
                                <div className={`w-2 h-2 rounded-full ${bundle.gatekeepers.site ? 'bg-emerald-400' : 'bg-slate-200'}`} title="Site"></div>
                            </div>
                        )}
                        
                        <span className={`px-3 py-1 text-[10px] font-bold uppercase tracking-widest rounded-full border ${
                            bundle.status === 'completed' ? 'bg-slate-100 text-slate-500 border-slate-200' :
                            bundle.status === 'active' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                            bundle.status === 'blocked' ? 'bg-rose-50 text-rose-700 border-rose-200' :
                            'bg-slate-50 text-slate-600 border-slate-200'
                        }`}>
                            {bundle.status}
                        </span>
                        {isExpanded ? <ChevronUp className="w-5 h-5 text-slate-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
                    </div>
                  </div>

                  {/* Expanded Content */}
                  <AnimatePresence>
                    {isExpanded && (
                      <motion.div 
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden border-t border-slate-100"
                      >
                        <div className="p-6 bg-slate-50/50">
                            
                            {/* LAYER 3: The Gatekeepers & Override */}
                            <div className="flex flex-col lg:flex-row gap-6 mb-6">
                                <div className="flex-1 bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
                                    <h4 className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-3">Transition Gatekeepers</h4>
                                    <div className="space-y-2">
                                        <button onClick={() => toggleGatekeeper(bundle.id, 'sof')} className="w-full flex items-center justify-between p-2 hover:bg-slate-50 rounded-lg transition-colors group">
                                            <span className="text-sm font-medium text-slate-700">SOF Frozen by Design</span>
                                            {bundle.gatekeepers.sof ? <CheckSquare className="w-5 h-5 text-emerald-500" /> : <div className="w-5 h-5 border-2 border-slate-300 rounded group-hover:border-slate-400 transition-colors"></div>}
                                        </button>
                                        <button onClick={() => toggleGatekeeper(bundle.id, 'payment')} className="w-full flex items-center justify-between p-2 hover:bg-slate-50 rounded-lg transition-colors group">
                                            <span className="text-sm font-medium text-slate-700">Stage Payment Cleared</span>
                                            {bundle.gatekeepers.payment ? <CheckSquare className="w-5 h-5 text-emerald-500" /> : <div className="w-5 h-5 border-2 border-slate-300 rounded group-hover:border-slate-400 transition-colors"></div>}
                                        </button>
                                        <button onClick={() => toggleGatekeeper(bundle.id, 'site')} className="w-full flex items-center justify-between p-2 hover:bg-slate-50 rounded-lg transition-colors group">
                                            <span className="text-sm font-medium text-slate-700">Site Cleared by Previous Team</span>
                                            {bundle.gatekeepers.site ? <CheckSquare className="w-5 h-5 text-emerald-500" /> : <div className="w-5 h-5 border-2 border-slate-300 rounded group-hover:border-slate-400 transition-colors"></div>}
                                        </button>
                                    </div>
                                </div>

                                {/* Ops Override Control */}
                                <div className="lg:w-72 bg-slate-900 p-4 rounded-xl border border-slate-800 shadow-sm flex flex-col justify-between relative overflow-hidden">
                                    <div className="absolute -right-4 -top-4 w-24 h-24 bg-amber-500/10 rounded-full blur-2xl"></div>
                                    <div>
                                        <h4 className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1">Manual Control</h4>
                                        <p className="text-xs text-slate-400 mb-4">Bypass gatekeepers to force-start execution.</p>
                                    </div>
                                    <button 
                                        onClick={() => toggleOverride(bundle.id)}
                                        className={`w-full py-2.5 px-4 rounded-lg text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-2 transition-all ${
                                            isOverridden 
                                            ? 'bg-amber-500 text-slate-900 shadow-[0_0_15px_rgba(245,158,11,0.3)]' 
                                            : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
                                        }`}
                                    >
                                        {isOverridden ? <Unlock className="w-4 h-4" /> : <Lock className="w-4 h-4" />}
                                        {isOverridden ? 'Override Active' : 'Engage Override'}
                                    </button>
                                </div>
                            </div>

                            {/* GFC DRAWING GATE SECTION */}
                            <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                                <div className="space-y-1">
                                    <h4 className="text-[10px] font-bold uppercase tracking-widest text-slate-400">GFC Drawing Gate</h4>
                                    <div className="flex flex-wrap items-center gap-2 mt-1.5">
                                        {typeof bundle.gate === 'object' && bundle.gate.requiresGfc ? (
                                            bundle.gate.status === 'ready' ? (
                                                <div className="flex flex-col gap-1">
                                                    <span className="text-xs font-bold text-emerald-700 flex items-center gap-1.5 bg-emerald-50 px-2.5 py-1 rounded-lg w-fit">
                                                        <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                                        GFC Drawing Released
                                                    </span>
                                                    <p className="text-[10px] text-slate-500 font-medium font-sans">
                                                        All required detailed fabrication packages are approved & Good-For-Construction.
                                                    </p>
                                                </div>
                                            ) : bundle.gate.status === 'in_progress' ? (
                                                <div className="space-y-1 bg-amber-50/50 p-2.5 rounded-lg border border-amber-100">
                                                    <span className="text-xs font-bold text-amber-700 flex items-center gap-1.5 bg-amber-50 px-2.5 py-1 rounded-lg w-fit">
                                                        <Unlock className="w-4 h-4 text-amber-500" />
                                                        Proceeding At Risk (Overridden)
                                                    </span>
                                                    {bundle.gate.overrideAudit && (
                                                        <p className="text-[10px] text-slate-600 font-medium leading-relaxed font-sans mt-1">
                                                            <strong>Authorized by:</strong> {bundle.gate.overrideAudit.by} on {new Date(bundle.gate.overrideAudit.at).toLocaleDateString()}
                                                            <br />
                                                            <strong>Justification:</strong> "{bundle.gate.overrideAudit.reason}"
                                                        </p>
                                                    )}
                                                </div>
                                            ) : (
                                                <div className="space-y-1.5">
                                                    <span className="text-xs font-bold text-rose-700 flex items-center gap-1.5 bg-rose-50 px-2.5 py-1 rounded-lg w-fit">
                                                        <ShieldAlert className="w-4 h-4 text-rose-500" />
                                                        Execution Gate Blocked (Pending GFCs)
                                                    </span>
                                                    <p className="text-xs text-rose-600 font-medium">
                                                        {bundle.gate.blockedReason}
                                                    </p>
                                                    {onNavigateDrawings && (
                                                        <button 
                                                            onClick={onNavigateDrawings}
                                                            className="text-xs font-bold text-indigo-600 hover:underline flex items-center gap-1 mt-1 shrink-0"
                                                        >
                                                            Open Drawing Tracker to issue GFC →
                                                        </button>
                                                    )}
                                                    {isOwner && (
                                                        <button 
                                                            onClick={() => setOverrideBundleId(bundle.id)}
                                                            className="px-3 py-1.5 bg-amber-500 hover:bg-amber-600 text-slate-950 font-extrabold text-[10px] uppercase tracking-wider rounded-lg transition-all shadow-sm flex items-center gap-1 mt-2.5"
                                                        >
                                                            <Unlock className="w-3.5 h-3.5" />
                                                            Proceed At Risk (Owner Override)
                                                        </button>
                                                    )}
                                                </div>
                                            )
                                        ) : (
                                            <span className="text-xs font-medium text-slate-500 italic">
                                                No GFC drawing requirements are defined for this category.
                                            </span>
                                        )}
                                    </div>
                                </div>

                                {/* Financial visibility split: ONLY Owner sees ₹ value of execution locked */}
                                {isOwner && typeof bundle.gate === 'object' && bundle.gate.unblocksValue > 0 && (
                                    <div className="bg-slate-50 border border-slate-100 px-4 py-2.5 rounded-xl text-right md:min-w-[140px] shrink-0">
                                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block leading-none mb-1">Unblocks Value</span>
                                        <span className="text-lg font-black text-slate-800 leading-none block font-sans">
                                            {formatINR(bundle.gate.unblocksValue)}
                                        </span>
                                    </div>
                                )}
                            </div>

                            {/* Action Intelligence (Only show if active or blocked) */}
                            {(bundle.status === 'active' || bundle.status === 'blocked') && (
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div className="bg-amber-50/50 border border-amber-200/50 p-4 rounded-xl">
                                        <p className="text-[10px] font-bold text-amber-600 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                                            <Zap className="w-3.5 h-3.5" /> Act Today
                                        </p>
                                        <p className="text-sm font-medium text-amber-900 leading-snug">{bundle.actToday}</p>
                                    </div>
                                    <div className="bg-rose-50/50 border border-rose-200/50 p-4 rounded-xl">
                                        <p className="text-[10px] font-bold text-rose-600 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                                            <AlertTriangle className="w-3.5 h-3.5" /> Breaks Tomorrow
                                        </p>
                                        <p className="text-sm font-medium text-rose-900 leading-snug">{bundle.breaksTomorrow}</p>
                                    </div>
                                </div>
                            )}

                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </motion.div>
        ) : activeTab === 'radar' ? (
          /* LAYER 4: Procurement Radar */
          <motion.div 
            key="radar"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden"
          >
            <div className="p-6 border-b border-slate-100 bg-slate-50/50 flex items-center justify-between">
                <div>
                    <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                        <PackageSearch className="w-5 h-5 text-slate-400" />
                        Procurement Radar
                    </h3>
                    <p className="text-xs text-slate-500 mt-1">Look-ahead based on BOQ lead times.</p>
                </div>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-left text-sm">
                    <thead className="bg-slate-50 text-slate-500 text-[10px] uppercase tracking-widest">
                    <tr>
                        <th className="p-4 font-bold border-b border-slate-200">Material / Item</th>
                        <th className="p-4 font-bold border-b border-slate-200">Target Bundle</th>
                        <th className="p-4 font-bold border-b border-slate-200">Lead Time</th>
                        <th className="p-4 font-bold border-b border-slate-200 text-right">Required Action</th>
                    </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                    {PROCUREMENT_RADAR.map((item, idx) => (
                        <tr key={idx} className="hover:bg-slate-50 transition-colors group">
                        <td className="p-4">
                            <p className="font-bold text-slate-800">{item.item}</p>
                        </td>
                        <td className="p-4">
                            <span className="text-xs font-medium text-slate-500 bg-slate-100 px-2 py-1 rounded">{item.bundle}</span>
                        </td>
                        <td className="p-4">
                            <div className="flex items-center gap-2">
                                <Clock className={`w-4 h-4 ${item.status === 'critical' ? 'text-rose-500' : item.status === 'warning' ? 'text-amber-500' : 'text-slate-400'}`} />
                                <span className={`font-mono font-bold ${item.status === 'critical' ? 'text-rose-600' : item.status === 'warning' ? 'text-amber-600' : 'text-slate-600'}`}>
                                    {item.leadTime}
                                </span>
                            </div>
                        </td>
                        <td className="p-4 text-right">
                            <button className={`px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider rounded border transition-colors ${
                                item.status === 'critical' ? 'bg-rose-50 text-rose-700 border-rose-200 hover:bg-rose-100' : 
                                item.status === 'warning' ? 'bg-amber-50 text-amber-700 border-amber-200 hover:bg-amber-100' : 
                                'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
                            }`}>
                                {item.action}
                            </button>
                        </td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>

      {/* OWNER OVERRIDE JUSTIFICATION MODAL */}
      <AnimatePresence>
        {overrideBundleId && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
            <motion.div 
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white rounded-2xl p-6 max-w-md w-full border border-slate-200 shadow-xl"
            >
              <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
                <Unlock className="w-5 h-5 text-amber-500" />
                Proceed at Risk Justification
              </h3>
              <p className="text-xs text-slate-500 mt-1">
                You are about to force-start an execution bundle before its GFC drawings are fully cleared. Provide a high-visibility, logged business justification.
              </p>
              
              <div className="mt-4">
                <label className="text-[10px] font-bold uppercase tracking-widest text-slate-400 block mb-1">
                  Reason for Override
                </label>
                <textarea
                  value={overrideReason}
                  onChange={(e) => setOverrideReason(e.target.value)}
                  placeholder="e.g. Client requested mockups site measurements cleared manually; procurement lead times require instant order"
                  rows={4}
                  className="w-full text-slate-800 text-sm p-3 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-amber-500/50"
                />
              </div>

              <div className="mt-6 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => {
                    setOverrideBundleId(null);
                    setOverrideReason('');
                  }}
                  className="px-4 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50 rounded-lg transition-colors border border-slate-200"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={() => handleProceedAtRisk(overrideBundleId, overrideReason)}
                  disabled={!overrideReason.trim()}
                  className="px-4 py-2 text-xs font-bold uppercase tracking-wider text-slate-950 bg-amber-500 hover:bg-amber-600 disabled:opacity-50 disabled:hover:bg-amber-500 rounded-lg transition-all shadow-sm"
                >
                  Authorize Override
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default ExecutionWorkspace;
