import { CivilScope, PropertyStatus, ProjectContext } from '../types';

// ============================================================================
// civilScope — what the site actually needs doing, as opposed to what the
// typology template happens to list.
//
// The BOQ generator used to read `config` ("3-BHK") and nothing else, so every
// three-bedroom flat produced the same carpentry list. A finished flat being
// refitted and a raw shell needing full masonry generated byte-identical
// bills, and a brief asking for "civil refresh to the entire flooring and all
// bathrooms" produced no civil line at all — the 1/2/3-BHK templates contain
// none, and nothing was there to add them.
//
// `Current Site State` was already on the form and read by exactly one place in
// the whole app, for a portal message. It sets the defaults here; the studio
// then corrects them per project, because the state of the site is a decent
// guess at the scope and never the whole of it.
// ============================================================================

export interface CivilScopeField {
  key: keyof CivilScope;
  label: string;
  /** What ticking it puts in the bill, in the estimator's own words. */
  detail: string;
}

/**
 * The scope switches, in the order they happen on site.
 *
 * Deliberately short. Every one of these changes which bank items are priced,
 * so a switch that changes nothing does not belong here.
 */
export const CIVIL_SCOPE_FIELDS: CivilScopeField[] = [
  { key: 'flooring',     label: 'Replace flooring',     detail: 'Lift and relay floors room by room, with tile budget and debris' },
  { key: 'bathrooms',    label: 'Overhaul bathrooms',   detail: 'BBC, waterproofing, wall and floor tiling, counter, sanitary and CP' },
  { key: 'kitchenCivil', label: 'Kitchen civil & dado', detail: 'Kitchen wall tiling and plumbing point shifts' },
  { key: 'rewiring',     label: 'Electrical rewiring',  detail: 'Point wiring across the carpet area, plus fittings at actuals' },
  { key: 'plumbing',     label: 'Re-run plumbing',      detail: 'New or shifted plumbing points through the wet areas' },
  { key: 'falseCeiling', label: 'False ceiling',        detail: 'POP ceiling, extent scaled by tier' },
  { key: 'painting',     label: 'Painting',             detail: 'Walls and ceilings across the carpet area' },
];

const ALL_OFF: CivilScope = {
  flooring: false, bathrooms: false, kitchenCivil: false,
  rewiring: false, plumbing: false, falseCeiling: false, painting: false,
};

/**
 * What each site state implies, before the studio touches it.
 *
 * Read straight off the three descriptions already printed on the form:
 * raw shell is "full masonry & civil required", semi-finished is "flooring
 * laid, plumbing ready", finished is "soft fit-out / modular only".
 */
export const DEFAULT_CIVIL_SCOPE: Record<PropertyStatus, CivilScope> = {
  // Nothing exists yet, so everything is in scope.
  raw_shell: {
    flooring: true, bathrooms: true, kitchenCivil: true,
    rewiring: true, plumbing: true, falseCeiling: true, painting: true,
  },
  // Floors are down and the lines are run; the wet areas still need fitting
  // out and the electricals still need their points.
  semi_finished: {
    ...ALL_OFF,
    bathrooms: true, kitchenCivil: true, rewiring: true,
    falseCeiling: true, painting: true,
  },
  // A refit: nothing is opened up unless the studio says so. This is the state
  // where the defaults are most often wrong on purpose — a client asking to
  // redo the floors and bathrooms of a finished flat is an ordinary brief, and
  // the switches are there to say so.
  finished: {
    ...ALL_OFF,
    falseCeiling: true, painting: true,
  },
};

/**
 * The scope in force for a project.
 *
 * An explicit choice always wins, including an explicit no. Only a project that
 * has never had the block touched falls back to the site state, so correcting a
 * default is not silently undone the next time the BOQ is regenerated.
 */
export function resolveCivilScope(ctx: Partial<ProjectContext> | undefined): CivilScope {
  const base = DEFAULT_CIVIL_SCOPE[ctx?.propertyStatus || 'finished'] || DEFAULT_CIVIL_SCOPE.finished;
  const saved = ctx?.civilScope;
  if (!saved) return { ...base };
  // Field by field, so a scope saved before a switch existed still picks up
  // that switch's default rather than reading as an explicit no.
  const out = { ...base };
  (Object.keys(base) as (keyof CivilScope)[]).forEach(k => {
    if (typeof saved[k] === 'boolean') out[k] = saved[k] as boolean;
  });
  return out;
}

/** True when the studio has overridden the site state's suggestion. */
export function isScopeCustomised(ctx: Partial<ProjectContext> | undefined): boolean {
  const base = DEFAULT_CIVIL_SCOPE[ctx?.propertyStatus || 'finished'];
  const live = resolveCivilScope(ctx);
  return (Object.keys(base) as (keyof CivilScope)[]).some(k => base[k] !== live[k]);
}

/** "Flooring, bathrooms and rewiring" — for a summary line or a rationale. */
export function describeCivilScope(scope: CivilScope): string {
  const on = CIVIL_SCOPE_FIELDS.filter(f => scope[f.key]).map(f => f.label.toLowerCase());
  if (!on.length) return 'no civil scope';
  if (on.length === 1) return on[0];
  return `${on.slice(0, -1).join(', ')} and ${on[on.length - 1]}`;
}


// ============================================================================
// Reading the brief
//
// The switches above are correct and they are still seven decisions. The studio
// has already written the requirement down in a sentence — "civil refresh to
// the entire flooring, bathrooms of the house" — and typing that same fact a
// second time as toggles is the kind of double entry that gets skipped, which
// is how a BOQ ends up not matching the brief.
//
// So the brief suggests; the studio confirms. Never applied silently: a switch
// that moved without anyone deciding is worse than one nobody set, because the
// bill changes and no one knows why.
// ============================================================================

interface ScopeCue {
  key: keyof CivilScope;
  /** Matched against the brief. Kept narrow — a false positive prices work. */
  test: RegExp;
}

const SCOPE_CUES: ScopeCue[] = [
  /*
    Deliberately narrow. A bare "tiles" used to match here, so "kitchen dado
    tiles" priced a whole-flat floor replacement — six figures of work nobody
    asked for. A cue that fires on the wrong word costs more than one that stays
    silent and lets the site-state default stand.
  */
  { key: 'flooring',     test: /\bfloor(ing|s)?\b|\bvitrified\b|\bre-?tile\s+the\s+(house|flat|floors?)\b|\b(wooden|laminate|marble)\s+floor/i },
  { key: 'bathrooms',    test: /\bbath(room)?s?\b|\btoilets?\b|\bwashrooms?\b|\bwc\b|\bsanitary\b|\bwet area/i },
  { key: 'kitchenCivil', test: /\bkitchen\b.*\b(civil|dado|tiles?|counter|platform)\b|\b(civil|dado)\b.*\bkitchen\b/i },
  { key: 'rewiring',     test: /\brewir|\bre-wir|\bwiring\b|\belectrical(s)?\b|\bpoints?\b.*\belectric|\bswitch(es|board)/i },
  { key: 'plumbing',     test: /\bplumb\w*|\bpipe(line|s)?\b|\bwater\s?line/i },
  { key: 'falseCeiling', test: /\bfalse ceiling\b|\bpop\b|\bceiling\b/i },
  { key: 'painting',     test: /\bpaint\w*|\bputty\b|\bprimer\b/i },
];

/** Phrases that mean the opposite, checked before the cue that they qualify. */
const NEGATIONS = /\b(no|not|without|exclude[sd]?|excluding|skip|leave|retain|keep\s+existing|existing|as[- ]is|untouched|unchanged|intact|stays?|remains?|no\s+change)\b/i;

export interface ScopeSuggestion {
  key: keyof CivilScope;
  value: boolean;
  /** The words in the brief that led here, so the studio can judge it. */
  quote: string;
}

/**
 * What the brief implies, sentence by sentence.
 *
 * Split on sentences so a negation only reaches the clause it belongs to —
 * "redo all the flooring, no work to the bathrooms" must not switch the
 * flooring off. Returns nothing rather than guessing when the brief is silent
 * on a trade; silence is not a no, it just leaves the site-state default.
 */
export function suggestScopeFromBrief(brief: string | undefined): ScopeSuggestion[] {
  const text = (brief || '').trim();
  if (text.length < 8) return [];

  const clauses = text.split(/[.;\n]+|,(?=\s*(?:no|not|without|exclude|excluding|skip)\b)/i)
    .map(c => c.trim())
    .filter(Boolean);

  const found = new Map<keyof CivilScope, ScopeSuggestion>();
  clauses.forEach(clause => {
    const negated = NEGATIONS.test(clause);
    SCOPE_CUES.forEach(cue => {
      const m = clause.match(cue.test);
      if (!m) return;
      // A later, more explicit clause wins over an earlier one.
      found.set(cue.key, {
        key: cue.key,
        value: !negated,
        quote: clause.length > 90 ? clause.slice(0, 87).trimEnd() + '…' : clause,
      });
    });
  });

  return Array.from(found.values());
}

/** The suggestions that would actually change something. */
export function pendingSuggestions(ctx: Partial<ProjectContext> | undefined): ScopeSuggestion[] {
  const live = resolveCivilScope(ctx);
  return suggestScopeFromBrief(ctx?.clientBrief).filter(sug => live[sug.key] !== sug.value);
}

/** Apply them, leaving every switch the brief was silent about alone. */
export function applySuggestions(ctx: Partial<ProjectContext> | undefined, suggestions: ScopeSuggestion[]): CivilScope {
  const next = resolveCivilScope(ctx);
  suggestions.forEach(sug => { next[sug.key] = sug.value; });
  return next;
}
